export const LogsColums = [
    { name: "Log ID", internal: 'log_id', isSort: true },
    { name: "Log Date", internal: 'log_date', isSort: true },
    { name: "Database Name", internal: 'db_name', isSort: true },
    { name: "Application Server", internal: 'appl_server', isSort: true },
    { name: "Service Name", internal: 'service_name', isSort: true },
    { name: "Session ID", internal: 'session_id', isSort: true },
    { name: "User ID", internal: 'user_id', isSort: true },
    { name: "User Full Name", internal: 'user_full_name', isSort: true },
    { name: "IP Address", internal: 'ip_address', isSort: true },
    { name: "User Agent", internal: 'user_agent', isSort: true },
    { name: "Message", internal: 'message', isSort: true },
    { name: "Generic Schema ID", internal: 'generic_schema_id', isSort: true },
    { name: "EF Module ID", internal: 'ef_module_id', isSort: true },
    { name: "EF Request ID", internal: 'ef_request_id', isSort: true },
    { name: "Event Start Date", internal: 'event_start_date', isSort: true },
    { name: "Event Complete Date", internal: 'event_complete_date', isSort: true },
    { name: "Event Elapsed Time", internal: 'event_elapsed_time', isSort: true },
    { name: "Event ID", internal: 'event_id', isSort: true },
    { name: "Status", internal: 'status', isSort: true },
    { name: "Has Error", internal: 'has_error', isSort: true },
    { name: "Error Message", internal: 'error_message', isSort: true }
];
